{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "478568ee-005d-46e8-8789-ca2d0a276028",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "os.chdir(\"C:\\\\Users\\\\Barakat Ogunjoun\\\\OneDrive\\\\Desktop\\\\BPA\\\\scripts\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "12cb54dd-28ab-4f4c-855b-af8c287ac7e8",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Import Libraries\n",
    "import pandas as pd\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "95a23afe-fd61-40fe-94a3-d28ff2d285d8",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Unnamed: 0</th>\n",
       "      <th>Idő</th>\n",
       "      <th>Befejezés</th>\n",
       "      <th>Forrás</th>\n",
       "      <th>Változtatott-e önszántából munkahelyet 2022. január 1. óta?</th>\n",
       "      <th>Rendezze sorrendbe fontosság szerint az alábbi, a munkához kapcsolódó értékeket. A sorba rendezéshez használjon csúszkát, ne a nyilakat!\\nMit tartott elsősorban, másodsorban stb. fontosnak, amikor munkahelyet változtatott? x Kevés stresszel járó munka</th>\n",
       "      <th>Rendezze sorrendbe fontosság szerint az alábbi, a munkához kapcsolódó értékeket. A sorba rendezéshez használjon csúszkát, ne a nyilakat!\\nMit tartott elsősorban, másodsorban stb. fontosnak, amikor munkahelyet változtatott? x Hosszú szabadság</th>\n",
       "      <th>Rendezze sorrendbe fontosság szerint az alábbi, a munkához kapcsolódó értékeket. A sorba rendezéshez használjon csúszkát, ne a nyilakat!\\nMit tartott elsősorban, másodsorban stb. fontosnak, amikor munkahelyet változtatott? x Szakmai fejlődési lehetőség</th>\n",
       "      <th>Rendezze sorrendbe fontosság szerint az alábbi, a munkához kapcsolódó értékeket. A sorba rendezéshez használjon csúszkát, ne a nyilakat!\\nMit tartott elsősorban, másodsorban stb. fontosnak, amikor munkahelyet változtatott? x Felemelkedési lehetőség a hierarchiában</th>\n",
       "      <th>Rendezze sorrendbe fontosság szerint az alábbi, a munkához kapcsolódó értékeket. A sorba rendezéshez használjon csúszkát, ne a nyilakat!\\nMit tartott elsősorban, másodsorban stb. fontosnak, amikor munkahelyet változtatott? x Biztos munkahely (nem kell attól tartanom, hogy munkanélkülivé válok)</th>\n",
       "      <th>...</th>\n",
       "      <th>Mennyire tartja valószínűnek, hogy önszántából munkahelyet változtat?.1</th>\n",
       "      <th>Mi az oka annak, hogy bár szándékában áll, mégsem valószínű, hogy önszántából  munkahelyet változtat?\\n(Ha nem áll fenn ez az ellentmondás, legyen a válasza: \"tárgytalan\"!).1</th>\n",
       "      <th>Az Önt foglalkoztató szervezet mérete:</th>\n",
       "      <th>Melyik szektorhoz tartozik a szervezete?</th>\n",
       "      <th>Mikor született?.1</th>\n",
       "      <th>Az Ön neme:.1</th>\n",
       "      <th>A legmagasabb iskolai végzettsége:.1</th>\n",
       "      <th>Az Ön beosztása:.1</th>\n",
       "      <th>Mi az Ön Neptun-kódja (vagy aki felkérte Önt a kitöltésre):</th>\n",
       "      <th>Melyik egyetemen hallgató Ön (vagy aki felkérte Önt a kitöltésre):</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2023-11-14</td>\n",
       "      <td>11:57:06</td>\n",
       "      <td>00:06:50</td>\n",
       "      <td>Közvetlen link</td>\n",
       "      <td>Nem</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>Valószínűnek tartom, hogy felmondok</td>\n",
       "      <td>Vezetés</td>\n",
       "      <td>A foglalkoztatottak száma 500 fölött van</td>\n",
       "      <td>Ipar</td>\n",
       "      <td>1965 és 1979 között</td>\n",
       "      <td>Férfi</td>\n",
       "      <td>Középiskolai</td>\n",
       "      <td>Nincs beosztottam</td>\n",
       "      <td>H4Q8QN</td>\n",
       "      <td>Nem tudom/nem releváns</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2023-11-14</td>\n",
       "      <td>09:37:04</td>\n",
       "      <td>00:15:04</td>\n",
       "      <td>Közvetlen link</td>\n",
       "      <td>Nem</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>Biztosan nem mondok fel</td>\n",
       "      <td>Tárgytalan</td>\n",
       "      <td>A foglalkoztatottak száma 500 fölött van</td>\n",
       "      <td>Ipar</td>\n",
       "      <td>1965 és 1979 között</td>\n",
       "      <td>Nő</td>\n",
       "      <td>Középiskolai</td>\n",
       "      <td>Nincs beosztottam</td>\n",
       "      <td>H4Q8QN</td>\n",
       "      <td>Nem tudom/nem releváns</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2023-11-14</td>\n",
       "      <td>09:22:35</td>\n",
       "      <td>00:12:18</td>\n",
       "      <td>Közvetlen link</td>\n",
       "      <td>Igen</td>\n",
       "      <td>20.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>16.0</td>\n",
       "      <td>10.0</td>\n",
       "      <td>15.0</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>H4Q8QN</td>\n",
       "      <td>Széchenyi István Egyetem</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2023-11-14</td>\n",
       "      <td>09:16:23</td>\n",
       "      <td>00:07:27</td>\n",
       "      <td>Közvetlen link</td>\n",
       "      <td>Nem</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>Nem tartom valószínűnek</td>\n",
       "      <td>Tárgytalan</td>\n",
       "      <td>A foglalkoztatottak száma 500 fölött van</td>\n",
       "      <td>Szolgáltató</td>\n",
       "      <td>1995 és 2009 között</td>\n",
       "      <td>Nő</td>\n",
       "      <td>Középiskolai</td>\n",
       "      <td>Nincs beosztottam</td>\n",
       "      <td>H4Q8QN</td>\n",
       "      <td>Széchenyi István Egyetem</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2023-11-14</td>\n",
       "      <td>09:14:13</td>\n",
       "      <td>00:05:44</td>\n",
       "      <td>Közvetlen link</td>\n",
       "      <td>Nem</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>Valószínűnek tartom, hogy felmondok</td>\n",
       "      <td>tárgytalan</td>\n",
       "      <td>A foglalkoztatottak száma 11 és 50 között van</td>\n",
       "      <td>Ipar</td>\n",
       "      <td>1995 és 2009 között</td>\n",
       "      <td>Férfi</td>\n",
       "      <td>Felsőfokú</td>\n",
       "      <td>Nincs beosztottam</td>\n",
       "      <td>H4Q8QN</td>\n",
       "      <td>Széchenyi István Egyetem</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 111 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "   Unnamed: 0       Idő Befejezés          Forrás  \\\n",
       "0  2023-11-14  11:57:06  00:06:50  Közvetlen link   \n",
       "1  2023-11-14  09:37:04  00:15:04  Közvetlen link   \n",
       "2  2023-11-14  09:22:35  00:12:18  Közvetlen link   \n",
       "3  2023-11-14  09:16:23  00:07:27  Közvetlen link   \n",
       "4  2023-11-14  09:14:13  00:05:44  Közvetlen link   \n",
       "\n",
       "  Változtatott-e önszántából munkahelyet 2022. január 1. óta?  \\\n",
       "0                                                Nem            \n",
       "1                                                Nem            \n",
       "2                                               Igen            \n",
       "3                                                Nem            \n",
       "4                                                Nem            \n",
       "\n",
       "   Rendezze sorrendbe fontosság szerint az alábbi, a munkához kapcsolódó értékeket. A sorba rendezéshez használjon csúszkát, ne a nyilakat!\\nMit tartott elsősorban, másodsorban stb. fontosnak, amikor munkahelyet változtatott? x Kevés stresszel járó munka  \\\n",
       "0                                                NaN                                                                                                                                                                                                             \n",
       "1                                                NaN                                                                                                                                                                                                             \n",
       "2                                               20.0                                                                                                                                                                                                             \n",
       "3                                                NaN                                                                                                                                                                                                             \n",
       "4                                                NaN                                                                                                                                                                                                             \n",
       "\n",
       "   Rendezze sorrendbe fontosság szerint az alábbi, a munkához kapcsolódó értékeket. A sorba rendezéshez használjon csúszkát, ne a nyilakat!\\nMit tartott elsősorban, másodsorban stb. fontosnak, amikor munkahelyet változtatott? x Hosszú szabadság  \\\n",
       "0                                                NaN                                                                                                                                                                                                   \n",
       "1                                                NaN                                                                                                                                                                                                   \n",
       "2                                                1.0                                                                                                                                                                                                   \n",
       "3                                                NaN                                                                                                                                                                                                   \n",
       "4                                                NaN                                                                                                                                                                                                   \n",
       "\n",
       "   Rendezze sorrendbe fontosság szerint az alábbi, a munkához kapcsolódó értékeket. A sorba rendezéshez használjon csúszkát, ne a nyilakat!\\nMit tartott elsősorban, másodsorban stb. fontosnak, amikor munkahelyet változtatott? x Szakmai fejlődési lehetőség  \\\n",
       "0                                                NaN                                                                                                                                                                                                              \n",
       "1                                                NaN                                                                                                                                                                                                              \n",
       "2                                               16.0                                                                                                                                                                                                              \n",
       "3                                                NaN                                                                                                                                                                                                              \n",
       "4                                                NaN                                                                                                                                                                                                              \n",
       "\n",
       "   Rendezze sorrendbe fontosság szerint az alábbi, a munkához kapcsolódó értékeket. A sorba rendezéshez használjon csúszkát, ne a nyilakat!\\nMit tartott elsősorban, másodsorban stb. fontosnak, amikor munkahelyet változtatott? x Felemelkedési lehetőség a hierarchiában  \\\n",
       "0                                                NaN                                                                                                                                                                                                                          \n",
       "1                                                NaN                                                                                                                                                                                                                          \n",
       "2                                               10.0                                                                                                                                                                                                                          \n",
       "3                                                NaN                                                                                                                                                                                                                          \n",
       "4                                                NaN                                                                                                                                                                                                                          \n",
       "\n",
       "   Rendezze sorrendbe fontosság szerint az alábbi, a munkához kapcsolódó értékeket. A sorba rendezéshez használjon csúszkát, ne a nyilakat!\\nMit tartott elsősorban, másodsorban stb. fontosnak, amikor munkahelyet változtatott? x Biztos munkahely (nem kell attól tartanom, hogy munkanélkülivé válok)  \\\n",
       "0                                                NaN                                                                                                                                                                                                                                                        \n",
       "1                                                NaN                                                                                                                                                                                                                                                        \n",
       "2                                               15.0                                                                                                                                                                                                                                                        \n",
       "3                                                NaN                                                                                                                                                                                                                                                        \n",
       "4                                                NaN                                                                                                                                                                                                                                                        \n",
       "\n",
       "   ...  \\\n",
       "0  ...   \n",
       "1  ...   \n",
       "2  ...   \n",
       "3  ...   \n",
       "4  ...   \n",
       "\n",
       "   Mennyire tartja valószínűnek, hogy önszántából munkahelyet változtat?.1  \\\n",
       "0                Valószínűnek tartom, hogy felmondok                         \n",
       "1                            Biztosan nem mondok fel                         \n",
       "2                                                NaN                         \n",
       "3                            Nem tartom valószínűnek                         \n",
       "4                Valószínűnek tartom, hogy felmondok                         \n",
       "\n",
       "   Mi az oka annak, hogy bár szándékában áll, mégsem valószínű, hogy önszántából  munkahelyet változtat?\\n(Ha nem áll fenn ez az ellentmondás, legyen a válasza: \"tárgytalan\"!).1  \\\n",
       "0                                           Vezetés                                                                                                                                 \n",
       "1                                         Tárgytalan                                                                                                                                \n",
       "2                                                NaN                                                                                                                                \n",
       "3                                        Tárgytalan                                                                                                                                 \n",
       "4                                         tárgytalan                                                                                                                                \n",
       "\n",
       "          Az Önt foglalkoztató szervezet mérete:  \\\n",
       "0       A foglalkoztatottak száma 500 fölött van   \n",
       "1       A foglalkoztatottak száma 500 fölött van   \n",
       "2                                            NaN   \n",
       "3       A foglalkoztatottak száma 500 fölött van   \n",
       "4  A foglalkoztatottak száma 11 és 50 között van   \n",
       "\n",
       "   Melyik szektorhoz tartozik a szervezete?   Mikor született?.1  \\\n",
       "0                                      Ipar  1965 és 1979 között   \n",
       "1                                      Ipar  1965 és 1979 között   \n",
       "2                                       NaN                  NaN   \n",
       "3                               Szolgáltató  1995 és 2009 között   \n",
       "4                                      Ipar  1995 és 2009 között   \n",
       "\n",
       "   Az Ön neme:.1  A legmagasabb iskolai végzettsége:.1  Az Ön beosztása:.1  \\\n",
       "0          Férfi                          Középiskolai   Nincs beosztottam   \n",
       "1             Nő                          Középiskolai   Nincs beosztottam   \n",
       "2            NaN                                   NaN                 NaN   \n",
       "3             Nő                          Középiskolai   Nincs beosztottam   \n",
       "4          Férfi                             Felsőfokú   Nincs beosztottam   \n",
       "\n",
       "   Mi az Ön Neptun-kódja (vagy aki felkérte Önt a kitöltésre):  \\\n",
       "0                                             H4Q8QN             \n",
       "1                                             H4Q8QN             \n",
       "2                                             H4Q8QN             \n",
       "3                                             H4Q8QN             \n",
       "4                                             H4Q8QN             \n",
       "\n",
       "   Melyik egyetemen hallgató Ön (vagy aki felkérte Önt a kitöltésre):  \n",
       "0                             Nem tudom/nem releváns                   \n",
       "1                             Nem tudom/nem releváns                   \n",
       "2                           Széchenyi István Egyetem                   \n",
       "3                           Széchenyi István Egyetem                   \n",
       "4                           Széchenyi István Egyetem                   \n",
       "\n",
       "[5 rows x 111 columns]"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "file = \"2023-11-14-survey-data-a-szervezeti-kommunikacio-jelentosege-a-munkaero-megtartasaban(1).xlsx\"\n",
    "data = pd.read_excel(file, sheet_name = \"Data\")\n",
    "data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "8c233623-65e0-4296-9b78-8055568b1f4c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 333 entries, 0 to 332\n",
      "Columns: 111 entries, Unnamed: 0 to Melyik egyetemen hallgató Ön (vagy aki felkérte Önt a kitöltésre):\n",
      "dtypes: float64(40), object(71)\n",
      "memory usage: 288.9+ KB\n"
     ]
    }
   ],
   "source": [
    "data.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "2327cbec-12c2-4c90-8cf7-703c00f15494",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>C000</th>\n",
       "      <th>C001</th>\n",
       "      <th>C002</th>\n",
       "      <th>C003</th>\n",
       "      <th>C004</th>\n",
       "      <th>C005</th>\n",
       "      <th>C006</th>\n",
       "      <th>C007</th>\n",
       "      <th>C008</th>\n",
       "      <th>C009</th>\n",
       "      <th>...</th>\n",
       "      <th>C101</th>\n",
       "      <th>C102</th>\n",
       "      <th>C103</th>\n",
       "      <th>C104</th>\n",
       "      <th>C105</th>\n",
       "      <th>C106</th>\n",
       "      <th>C107</th>\n",
       "      <th>C108</th>\n",
       "      <th>C109</th>\n",
       "      <th>C110</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2023-11-14</td>\n",
       "      <td>11:57:06</td>\n",
       "      <td>00:06:50</td>\n",
       "      <td>Közvetlen link</td>\n",
       "      <td>Nem</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>Valószínűnek tartom, hogy felmondok</td>\n",
       "      <td>Vezetés</td>\n",
       "      <td>A foglalkoztatottak száma 500 fölött van</td>\n",
       "      <td>Ipar</td>\n",
       "      <td>1965 és 1979 között</td>\n",
       "      <td>Férfi</td>\n",
       "      <td>Középiskolai</td>\n",
       "      <td>Nincs beosztottam</td>\n",
       "      <td>H4Q8QN</td>\n",
       "      <td>Nem tudom/nem releváns</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2023-11-14</td>\n",
       "      <td>09:37:04</td>\n",
       "      <td>00:15:04</td>\n",
       "      <td>Közvetlen link</td>\n",
       "      <td>Nem</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>Biztosan nem mondok fel</td>\n",
       "      <td>Tárgytalan</td>\n",
       "      <td>A foglalkoztatottak száma 500 fölött van</td>\n",
       "      <td>Ipar</td>\n",
       "      <td>1965 és 1979 között</td>\n",
       "      <td>Nő</td>\n",
       "      <td>Középiskolai</td>\n",
       "      <td>Nincs beosztottam</td>\n",
       "      <td>H4Q8QN</td>\n",
       "      <td>Nem tudom/nem releváns</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2023-11-14</td>\n",
       "      <td>09:22:35</td>\n",
       "      <td>00:12:18</td>\n",
       "      <td>Közvetlen link</td>\n",
       "      <td>Igen</td>\n",
       "      <td>20.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>16.0</td>\n",
       "      <td>10.0</td>\n",
       "      <td>15.0</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>H4Q8QN</td>\n",
       "      <td>Széchenyi István Egyetem</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2023-11-14</td>\n",
       "      <td>09:16:23</td>\n",
       "      <td>00:07:27</td>\n",
       "      <td>Közvetlen link</td>\n",
       "      <td>Nem</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>Nem tartom valószínűnek</td>\n",
       "      <td>Tárgytalan</td>\n",
       "      <td>A foglalkoztatottak száma 500 fölött van</td>\n",
       "      <td>Szolgáltató</td>\n",
       "      <td>1995 és 2009 között</td>\n",
       "      <td>Nő</td>\n",
       "      <td>Középiskolai</td>\n",
       "      <td>Nincs beosztottam</td>\n",
       "      <td>H4Q8QN</td>\n",
       "      <td>Széchenyi István Egyetem</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2023-11-14</td>\n",
       "      <td>09:14:13</td>\n",
       "      <td>00:05:44</td>\n",
       "      <td>Közvetlen link</td>\n",
       "      <td>Nem</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>Valószínűnek tartom, hogy felmondok</td>\n",
       "      <td>tárgytalan</td>\n",
       "      <td>A foglalkoztatottak száma 11 és 50 között van</td>\n",
       "      <td>Ipar</td>\n",
       "      <td>1995 és 2009 között</td>\n",
       "      <td>Férfi</td>\n",
       "      <td>Felsőfokú</td>\n",
       "      <td>Nincs beosztottam</td>\n",
       "      <td>H4Q8QN</td>\n",
       "      <td>Széchenyi István Egyetem</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 111 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "         C000      C001      C002            C003  C004  C005  C006  C007  \\\n",
       "0  2023-11-14  11:57:06  00:06:50  Közvetlen link   Nem   NaN   NaN   NaN   \n",
       "1  2023-11-14  09:37:04  00:15:04  Közvetlen link   Nem   NaN   NaN   NaN   \n",
       "2  2023-11-14  09:22:35  00:12:18  Közvetlen link  Igen  20.0   1.0  16.0   \n",
       "3  2023-11-14  09:16:23  00:07:27  Közvetlen link   Nem   NaN   NaN   NaN   \n",
       "4  2023-11-14  09:14:13  00:05:44  Közvetlen link   Nem   NaN   NaN   NaN   \n",
       "\n",
       "   C008  C009  ...                                 C101         C102  \\\n",
       "0   NaN   NaN  ...  Valószínűnek tartom, hogy felmondok     Vezetés    \n",
       "1   NaN   NaN  ...              Biztosan nem mondok fel   Tárgytalan   \n",
       "2  10.0  15.0  ...                                  NaN          NaN   \n",
       "3   NaN   NaN  ...              Nem tartom valószínűnek  Tárgytalan    \n",
       "4   NaN   NaN  ...  Valószínűnek tartom, hogy felmondok   tárgytalan   \n",
       "\n",
       "                                            C103         C104  \\\n",
       "0       A foglalkoztatottak száma 500 fölött van         Ipar   \n",
       "1       A foglalkoztatottak száma 500 fölött van         Ipar   \n",
       "2                                            NaN          NaN   \n",
       "3       A foglalkoztatottak száma 500 fölött van  Szolgáltató   \n",
       "4  A foglalkoztatottak száma 11 és 50 között van         Ipar   \n",
       "\n",
       "                  C105   C106          C107               C108    C109  \\\n",
       "0  1965 és 1979 között  Férfi  Középiskolai  Nincs beosztottam  H4Q8QN   \n",
       "1  1965 és 1979 között     Nő  Középiskolai  Nincs beosztottam  H4Q8QN   \n",
       "2                  NaN    NaN           NaN                NaN  H4Q8QN   \n",
       "3  1995 és 2009 között     Nő  Középiskolai  Nincs beosztottam  H4Q8QN   \n",
       "4  1995 és 2009 között  Férfi     Felsőfokú  Nincs beosztottam  H4Q8QN   \n",
       "\n",
       "                       C110  \n",
       "0    Nem tudom/nem releváns  \n",
       "1    Nem tudom/nem releváns  \n",
       "2  Széchenyi István Egyetem  \n",
       "3  Széchenyi István Egyetem  \n",
       "4  Széchenyi István Egyetem  \n",
       "\n",
       "[5 rows x 111 columns]"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Rename columns to C999 format\n",
    "new_columns = {old_col: f'C{i:03d}' for i, old_col in enumerate(data.columns)}\n",
    "data = data.rename(columns=new_columns)\n",
    "data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "8bea93a6-5719-4f9e-baf3-fde94a1a9446",
   "metadata": {},
   "outputs": [],
   "source": [
    "# These are ordered to match the English questions list below.\n",
    "PASTEX_COLUMN_NAMES = [\n",
    "    \"C034\", # (a) regular meetings requiring physical presence or conducted online\n",
    "    \"C035\", # (b) professional briefings, discussions, and exchanges of opinion\n",
    "    \"C036\", # (c) opportunities to share new ideas and suggestions with supervisors and colleagues\n",
    "    \"C037\", # (d) the ability to freely express negative feedback\n",
    "    \"C038\", # (e) receiving positive feedback for good performance\n",
    "    \"C039\", # (f) informal conversations\n",
    "    \"C040\", # (g) honest and respectful communication between supervisors and subordinates, as well as among colleagues\n",
    "]\n",
    "\n",
    "# English descriptions of the PastEx questions, ordered to match the CXXX column IDs.\n",
    "QUESTIONS_ENGLISH_TRANSLATIONS = [\n",
    "    \"(a) regular meetings requiring physical presence or conducted online\",\n",
    "    \"(b) professional briefings, discussions, and exchanges of opinion\",\n",
    "    \"(c) opportunities to share new ideas and suggestions with supervisors and colleagues\",\n",
    "    \"(d) the ability to freely express negative feedback\",\n",
    "    \"(e) receiving positive feedback for good performance\",\n",
    "    \"(f) informal conversations\",\n",
    "    \"(g) honest and respectful communication between supervisors and subordinates, as well as among colleagues\",\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "310662c6-6017-4847-b89d-5ad41bcf7425",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "--- Unique Values for PastEx Variables ---\n",
      "\n",
      "Column: C034\n",
      "Unique values: [nan, 'Egyetértek', 'Egyáltalán nem értek egyet', 'Teljesen egyetértek', 'Nem értek egyet']\n",
      "\n",
      "Column: C035\n",
      "Unique values: [nan, 'Egyetértek', 'Teljesen egyetértek', 'Nem értek egyet', 'Egyáltalán nem értek egyet']\n",
      "\n",
      "Column: C036\n",
      "Unique values: [nan, 'Nem értek egyet', 'Egyáltalán nem értek egyet', 'Teljesen egyetértek', 'Egyetértek']\n",
      "\n",
      "Column: C037\n",
      "Unique values: [nan, 'Egyetértek', 'Nem értek egyet', 'Egyáltalán nem értek egyet', 'Teljesen egyetértek']\n",
      "\n",
      "Column: C038\n",
      "Unique values: [nan, 'Nem értek egyet', 'Egyáltalán nem értek egyet', 'Egyetértek', 'Teljesen egyetértek']\n",
      "\n",
      "Column: C039\n",
      "Unique values: [nan, 'Egyetértek', 'Teljesen egyetértek', 'Nem értek egyet', 'Egyáltalán nem értek egyet']\n",
      "\n",
      "Column: C040\n",
      "Unique values: [nan, 'Egyáltalán nem értek egyet', 'Nem értek egyet', 'Teljesen egyetértek', 'Egyetértek']\n"
     ]
    }
   ],
   "source": [
    "#Find the unique values of each PastEx Varible observed\n",
    "print(\"--- Unique Values for PastEx Variables ---\")\n",
    "for col_id in PASTEX_COLUMN_NAMES:\n",
    "    if col_id in data.columns:\n",
    "        unique_values = data[col_id].unique()\n",
    "        print(f\"\\nColumn: {col_id}\")\n",
    "        print(f\"Unique values: {unique_values.tolist()}\")\n",
    "    else:\n",
    "        print(f\"\\nWarning: PastEx Column ID '{col_id}' not found in the DataFrame after renaming.\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "53b105d5-2550-4299-abb7-8b2f6b29b703",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "| Question | Median |\n",
      "|----------|--------|\n",
      "| (a) regular meetings requiring physical presence or conducted online | 4.00 |\n",
      "| (b) professional briefings, discussions, and exchanges of opinion | 4.00 |\n",
      "| (c) opportunities to share new ideas and suggestions with supervisors and colleagues | 4.00 |\n",
      "| (d) the ability to freely express negative feedback | 4.00 |\n",
      "| (e) receiving positive feedback for good performance | 2.00 |\n",
      "| (f) informal conversations | 4.00 |\n",
      "| (g) honest and respectful communication between supervisors and subordinates, as well as among colleagues | 4.00 |\n"
     ]
    }
   ],
   "source": [
    "# Prepare a list to store the calculated medians\n",
    "medians = []\n",
    "\n",
    "# Calculate medians for each PastEx column after applying Likert mapping\n",
    "for col_id in PASTEX_COLUMN_NAMES:\n",
    "    if col_id in data.columns:\n",
    "        # Apply the Likert mapping and drop any NaN values that result from unmapped text\n",
    "        numeric_data = data[col_id].map(LIKERT_MAPPING).dropna()\n",
    "        if not numeric_data.empty:\n",
    "            medians.append(numeric_data.median())\n",
    "        else:\n",
    "            medians.append(np.nan) # Append NaN if no valid numeric data\n",
    "    else:\n",
    "        print(f\"Warning: Column ID '{col_id}' not found in the DataFrame after renaming. Skipping.\")\n",
    "        medians.append(np.nan) # Append NaN if column is missing\n",
    "\n",
    "# Output Markdown table\n",
    "print('| Question | Median |')\n",
    "print('|----------|--------|')\n",
    "for q, m in zip(QUESTIONS_ENGLISH_TRANSLATIONS, medians):\n",
    "    # Format median to 2 decimal places if it's a number, otherwise print 'N/A'\n",
    "    formatted_median = f\"{m:.2f}\" if pd.notna(m) else \"N/A\"\n",
    "    print(f'| {q} | {formatted_median} |')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a3c1b813-defa-4ddc-ba1f-9635910c1d7a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
